/**
 * Website Blueprint Engine v2.0 — True Generative Architecture
 *
 * ARCHITECTURE CHANGE:
 * Phase 3 no longer determines components by keyword-matching page names.
 * Instead it uses the rich per-page `recommendedSections` generated by Robert (Phase 1/2)
 * — each section already carries a `contentSpec` with business-specific content.
 *
 * This makes the Blueprint the faithful encoded representation of Robert's intent,
 * which Phase 4 then renders deterministically.
 *
 * Key rules:
 * - ZERO new LLM calls (100% deterministic transformation)
 * - page.recommendedSections → blueprint components with contentSpec preserved
 * - Keyword matching is a LAST RESORT fallback only, not primary logic
 * - contentSpec flows through blueprint → generator → renderer unchanged
 */

function generateWebsiteBlueprint(requirement, approvedRecommendations = [], reqId = null) {
  const correlationTag = reqId ? `[WB:${reqId}] ` : '[WebsiteBlueprintService] ';
  console.log(`${correlationTag}Generating Website Blueprint deterministically...`);

  if (!requirement || typeof requirement !== 'object') {
    throw new Error('Valid Phase 2 Requirement object is required to generate Website Blueprint.');
  }

  const approvedSet = new Set(
    Array.isArray(approvedRecommendations)
      ? approvedRecommendations.map((f) => f.toLowerCase().trim())
      : []
  );

  const rejectedSet = new Set(
    Array.isArray(requirement.rejectedRecommendations)
      ? requirement.rejectedRecommendations.map((f) => f.toLowerCase().trim())
      : []
  );

  // 1. Process Feature Ownership Matrix
  const userRequestedFeatures = (Array.isArray(requirement.userRequestedFeatures)
    ? [...requirement.userRequestedFeatures]
    : []).filter((f) => !rejectedSet.has(f.toLowerCase().trim()));

  const rawAiRecommended = Array.isArray(requirement.aiRecommendedFeatures)
    ? [...requirement.aiRecommendedFeatures]
    : [];

  const approvedRecFeatures = [];
  const unapprovedAiRecommendedFeatures = [];

  rawAiRecommended.forEach((feature) => {
    const fLower = feature.toLowerCase().trim();
    if (rejectedSet.has(fLower)) {
      return; // Excluded completely by user rejection
    }
    const isApproved = approvedSet.has(fLower);
    if (isApproved) {
      approvedRecFeatures.push(feature);
    } else {
      unapprovedAiRecommendedFeatures.push(feature);
    }
  });

  // 2. Extract contentStrategy from requirement (generated by Robert)
  const contentStrategy = requirement.contentStrategy || null;

  // 3. Process Pages & Page-Level Components
  let rawPages = Array.isArray(requirement.proposedPages) ? [...requirement.proposedPages] : [];
  const rawPrompt = (requirement.userIntent?.rawPrompt || requirement.businessType || '').toLowerCase();
  const isSingleLandingPage = /single page|one page|landing page|coming soon/i.test(rawPrompt);

  // Only decompose if it was NOT explicitly intended as a single landing page and has excessive grouped sections
  if (!isSingleLandingPage && rawPages.length === 1 && Array.isArray(rawPages[0].recommendedSections) && rawPages[0].recommendedSections.length >= 5) {
    const allSections = rawPages[0].recommendedSections;
    const heroAndStats = allSections.filter((s) => ['HeroBanner', 'HeroSplit', 'HeroMinimal', 'StatsCounter', 'FeatureGrid', 'ValuePropositionGrid', 'TestimonialsCarousel', 'ReviewsGrid', 'CallToActionBanner'].includes(s.type));
    const catalogAndServices = allSections.filter((s) => ['ItemCatalogGrid', 'RestaurantMenuCard', 'PricingPlansGrid', 'ServicesGrid', 'PortfolioGallery', 'HowItWorksGrid', 'ProcessSteps'].includes(s.type));
    const teamAndStory = allSections.filter((s) => ['TeamGrid', 'FacultyGrid', 'ContentSectionCard'].includes(s.type));
    const formsAndBooking = allSections.filter((s) => ['BookingForm', 'DemoRequestForm', 'ContactInquiryForm', 'CustomOrderForm', 'LocationHoursCard', 'GuideAccordion', 'FAQAccordion'].includes(s.type));

    if (catalogAndServices.length > 0 || formsAndBooking.length > 0) {
      const isCoaching = (requirement.industry || '').toLowerCase().includes('education') || (requirement.businessType || '').toLowerCase().includes('coaching') || (requirement.brandName || '').toLowerCase().includes('classes');
      const isDining = requirement.domainArchetype === 'RESTAURANT_CULINARY';
      const isStore = requirement.domainArchetype === 'ECOMMERCE_STORE';

      const p2Name = isDining ? 'Menu & Dining' : (isStore ? 'Products & Shop' : (isCoaching ? 'Courses & Batches' : 'Offerings & Features'));
      const p3Name = isCoaching ? 'Faculty & Admissions' : (isDining ? 'Reservations & Location' : (isStore ? 'Deals & Support' : 'Book & Contact'));

      const homeSections = [];
      const heroSection = allSections.find((s) => ['HeroBanner', 'HeroSplit', 'HeroMinimal'].includes(s.type)) || allSections[0];
      if (heroSection) homeSections.push(heroSection);

      const mainCatalog = allSections.find((s) => ['ItemCatalogGrid', 'RestaurantMenuCard', 'PricingPlansGrid'].includes(s.type));
      if (mainCatalog && !homeSections.includes(mainCatalog)) homeSections.push(mainCatalog);

      const statsOrFeature = allSections.filter((s) => ['StatsCounter', 'FeatureGrid', 'ValuePropositionGrid', 'TestimonialsCarousel', 'CallToActionBanner'].includes(s.type) && !homeSections.includes(s));
      homeSections.push(...statsOrFeature.slice(0, 3));

      rawPages = [
        {
          name: 'Home',
          slug: 'home',
          purpose: 'High-impact overview, featured offerings, quality pillars, and customer proof.',
          source: 'user_requested',
          recommendedSections: homeSections.length > 0 ? homeSections : [allSections[0]]
        },
        {
          name: p2Name,
          slug: p2Name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
          purpose: 'Complete catalog and structured offerings details.',
          source: 'user_requested',
          recommendedSections: catalogAndServices.length > 0 ? catalogAndServices : [allSections[1] || allSections[0]]
        },
        {
          name: p3Name,
          slug: p3Name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
          purpose: 'Interactive bookings, team background, FAQs, and contact inquiry.',
          source: 'user_requested',
          recommendedSections: (teamAndStory.length > 0 || formsAndBooking.length > 0) ? [...teamAndStory, ...formsAndBooking] : [allSections[allSections.length - 1]]
        }
      ];
    }
  }

  const blueprintPages = rawPages.map((page, idx) => {
    const pageName = page.name || `Page ${idx + 1}`;
    const pagePurpose = page.purpose || 'Page overview';
    const pageUserJourney = page.userJourney || '';
    let pageSource = page.source === 'user_requested' ? 'user_requested' : 'ai_recommended';

    if (pageSource === 'ai_recommended' && approvedSet.has(pageName.toLowerCase().trim())) {
      pageSource = 'approved_recommendation';
    }

    // Core generative change: use Robert's recommendedSections if present
    const components = buildPageComponents(
      page,
      pageName,
      pagePurpose,
      pageSource,
      userRequestedFeatures,
      approvedRecFeatures,
      contentStrategy,
      requirement.businessType,
      requirement.websiteType
    );

    return {
      name: pageName,
      slug: page.slug || pageName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      purpose: pagePurpose,
      userJourney: pageUserJourney,
      source: pageSource,
      components
    };
  });

  // 4. Process Navigation
  const headerLinks = blueprintPages.map((p) => ({
    label: p.name,
    pageName: p.name,
    slug: p.slug
  }));
  const footerLinks = blueprintPages.map((p) => ({
    label: p.name,
    pageName: p.name,
    slug: p.slug
  }));

  // 5. Synthesize CTAs from contentStrategy (if available) or from features
  const ctaRequirements = synthesizeCTAs(contentStrategy, userRequestedFeatures, approvedRecFeatures, requirement.businessType);

  // 6. Contact requirements
  const allFeaturesLower = [...userRequestedFeatures, ...approvedRecFeatures].map((f) => f.toLowerCase());
  const promptText = (userRequestedFeatures.join(' ') + ' ' + (requirement.businessType || '')).toLowerCase();
  const isWhatsAppRejected = Array.from(rejectedSet).some((r) => r.includes('whatsapp'));

  const contactRequirements = {
    hasContactForm: requirement.functionalRequirements?.contactForms !== false,
    hasWhatsApp: !isWhatsAppRejected && (allFeaturesLower.some((f) => f.includes('whatsapp')) || promptText.includes('whatsapp')),
    hasLocationDetails: allFeaturesLower.some((f) => f.includes('location') || f.includes('address') || f.includes('hours')) || promptText.includes('location')
  };

  // 7. Payment/Checkout/Auth specs
  const paymentCheckoutSpec = {
    paymentRequired: !!requirement.paymentSpec?.paymentRequired,
    paymentStatus: requirement.paymentSpec?.status || 'not_requested',
    supportedMethods: requirement.paymentSpec?.supportedMethods || [],
    checkoutRequired: !!requirement.checkoutSpec?.checkoutRequired,
    checkoutStatus: requirement.checkoutSpec?.status || 'not_requested',
    authRequired: !!requirement.functionalRequirements?.authRequired
  };

  // 8. Assemble Complete Blueprint
  const blueprint = {
    blueprintId: `bp_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
    createdAt: new Date().toISOString(),
    websiteIdentity: {
      title: requirement.brandName || requirement.businessType || 'Custom Web Application',
      businessType: requirement.businessType || 'General Business',
      businessNiche: requirement.businessNiche || '',
      industry: requirement.industry || 'General Business',
      appType: requirement.appType || 'marketing_website',
      targetAudience: Array.isArray(requirement.targetAudience) ? requirement.targetAudience : ['General Customers'],
      uniqueValueProposition: requirement.uniqueValueProposition || '',
      primaryGoal: requirement.primaryGoal || '',
      contentTone: requirement.contentTone || 'professional'
    },
    domainArchetype: requirement.domainArchetype || 'CUSTOM_WEB_APP',
    inferredCapabilities: Array.isArray(requirement.inferredCapabilities) ? requirement.inferredCapabilities : [],
    userJourney: Array.isArray(requirement.userIntent?.primaryUserJourney) ? requirement.userIntent.primaryUserJourney : [],
    appType: requirement.appType || 'interactive_app',
    websiteType: requirement.websiteType || (requirement.appType === 'interactive_app' ? 'Web Application' : 'Business Website'),
    designSpec: {
      theme: requirement.designPreferences?.theme || 'Modern Light',
      primaryColor: requirement.designPreferences?.primaryColor || '#6366F1',
      secondaryColor: requirement.designPreferences?.secondaryColor || '#4F46E5',
      accentColor: requirement.designPreferences?.accentColor || '',
      backgroundColor: requirement.designPreferences?.backgroundColor || '',
      typography: requirement.designPreferences?.typography || 'Inter',
      headingTypography: requirement.designPreferences?.headingTypography || '',
      cardStyle: requirement.designPreferences?.cardStyle || 'clean-flat',
      buttonStyle: requirement.designPreferences?.buttonStyle || 'pill',
      heroStyle: requirement.designPreferences?.heroStyle || 'split-left',
      spacingDensity: requirement.designPreferences?.spacingDensity || 'comfortable',
      visualTone: requirement.designPreferences?.visualTone || 'professional',
      layoutStyle: 'Responsive Container Grid',
      sources: requirement.designPreferences?.sources || {}
    },
    featureMatrix: {
      userRequestedFeatures,
      aiRecommendedFeatures: unapprovedAiRecommendedFeatures,
      approvedRecommendations: approvedRecFeatures
    },
    contentStrategy,
    pages: blueprintPages,
    navigationSpec: { headerLinks, footerLinks },
    ctaRequirements,
    imagerySpec: {
      requiresImages: Array.isArray(contentStrategy?.imageryRequirements) && contentStrategy.imageryRequirements.length > 0,
      imageryStyle: contentStrategy?.imageryStyle || 'clean modern photography',
      imageRoles: Array.isArray(contentStrategy?.imageryRequirements) ? contentStrategy.imageryRequirements : []
    },
    contactRequirements,
    paymentCheckoutSpec,
    validationStatus: validateBlueprintSchema({ blueprintPages, userRequestedFeatures, paymentCheckoutSpec }),
    // Visual design fingerprint & Approved Asset Pool — passed through to the code emitter
    visualDesignSpec: requirement.visualDesignSpec || null,
    approvedAssetPool: requirement.approvedAssetPool || {}
  };

  console.log(`${correlationTag}Website Blueprint generated successfully. Pages: ${blueprintPages.length}, User Features: ${userRequestedFeatures.length}, Approved Recs: ${approvedRecFeatures.length}`);
  return blueprint;
}

/**
 * Builds page-level component list.
 *
 * PRIMARY PATH: Use Robert's recommendedSections (with embedded contentSpec).
 * FALLBACK PATH: Use page purpose + business type to determine sections.
 *   This fallback does NOT use page-name keyword matching as the primary driver.
 */
function buildPageComponents(page, pageName, pagePurpose, pageSource, userRequestedFeatures, approvedRecFeatures, contentStrategy, businessType, websiteType) {
  const pageSlug = (page.slug || pageName.toLowerCase().replace(/[^a-z0-9]/g, '_'));
  const components = [];

  // === PRIMARY PATH: Use Robert's recommendedSections or User's edited page.components ===
  const customSections = (Array.isArray(page.components) && page.components.length > 0)
    ? page.components
    : (Array.isArray(page.recommendedSections) && page.recommendedSections.length > 0)
      ? page.recommendedSections
      : null;

  if (customSections) {
    customSections.forEach((section, idx) => {
      components.push({
        id: section.id || `comp_${pageSlug}_${idx}_${section.type || 'section'}`.toLowerCase().replace(/[^a-z0-9_]/g, '_'),
        type: section.type || 'ContentSectionCard',
        title: section.title || `${pageName} Section`,
        purpose: section.purpose || pagePurpose,
        source: section.source || pageSource,
        // contentSpec, approvedAssetId & pre-generated imageUrl flow through unchanged
        contentSpec: section.contentSpec || null,
        imageUrl: section.imageUrl || null,
        approvedAssetId: section.approvedAssetId || null
      });
    });
    return components;
  }

  // === FALLBACK PATH: Business-aware section synthesis ===
  // Used when LLM didn't provide recommendedSections (e.g. fallback mode)
  // Note: even here we use business CONTEXT, not just page name keywords

  const nameLower = pageName.toLowerCase();
  const purposeLower = pagePurpose.toLowerCase();
  const businessLower = (businessType || '').toLowerCase();
  const websiteLower = (websiteType || '').toLowerCase();

  const isHomePage = nameLower === 'home' || nameLower.includes('home') || nameLower.includes('landing');
  const isMenuPage = nameLower.includes('menu') || purposeLower.includes('menu') || purposeLower.includes('dish');
  const isGalleryPage = nameLower.includes('portfolio') || nameLower.includes('gallery') || nameLower.includes('work') || purposeLower.includes('portfolio');
  const isPricingPage = nameLower.includes('pricing') || nameLower.includes('plan') || purposeLower.includes('pricing');
  const isBookingPage = nameLower.includes('book') || nameLower.includes('reserv') || nameLower.includes('demo') || purposeLower.includes('booking') || purposeLower.includes('reserv');
  const isContactPage = nameLower.includes('contact') || nameLower.includes('support') || purposeLower.includes('contact');
  const isAboutPage = nameLower.includes('about') || nameLower.includes('story') || purposeLower.includes('story') || purposeLower.includes('history');
  const isFeaturePage = nameLower.includes('feature') || nameLower.includes('capabilities') || purposeLower.includes('features');
  const isCatalogPage = nameLower.includes('catalog') || nameLower.includes('products') || nameLower.includes('shop') || purposeLower.includes('catalog');
  const isServicesPage = nameLower.includes('service') || purposeLower.includes('services');
  const isComparePage = nameLower.includes('compare') || nameLower.includes('specs') || purposeLower.includes('comparison');
  const isExperiencesPage = nameLower.includes('experience') || nameLower.includes('amenity') || nameLower.includes('amenities');
  const isOrderPage = nameLower.includes('order') || nameLower.includes('custom') || purposeLower.includes('custom order');
  const isRoomPage = nameLower.includes('room') || nameLower.includes('suite') || nameLower.includes('villa') || purposeLower.includes('room');

  const isRestaurant = businessLower.includes('restaurant') || businessLower.includes('dining') || businessLower.includes('bistro') || websiteLower.includes('restaurant');
  const isHotel = businessLower.includes('hotel') || businessLower.includes('resort') || websiteLower.includes('hotel');
  const isSaaS = businessLower.includes('saas') || businessLower.includes('software') || websiteLower.includes('saas');
  const isPortfolio = businessLower.includes('photographer') || businessLower.includes('portfolio') || businessLower.includes('creative');
  const isBakery = businessLower.includes('bakery') || businessLower.includes('confection') || businessLower.includes('cake');
  const isFitness = businessLower.includes('fitness') || businessLower.includes('coaching') || businessLower.includes('trainer');

  // Hero component — always first
  const heroType = isPortfolio ? 'HeroSplit' : (isHotel ? 'HeroBanner' : 'HeroBanner');
  const heroContentSpec = contentStrategy?.heroContent
    ? { headline: contentStrategy.heroContent.headline, subheadline: contentStrategy.heroContent.subheadline }
    : { headline: `${pageName}`, subheadline: pagePurpose };

  components.push({
    id: `comp_hero_${pageSlug}`,
    type: heroType,
    title: `${pageName} Hero`,
    purpose: `Introduction and hero for ${pageName}`,
    source: pageSource,
    contentSpec: heroContentSpec
  });

  if (isHomePage) {
    if (isFitness) {
      components.push({ id: `comp_stats_${pageSlug}`, type: 'StatsCounter', title: 'Coaching Results', purpose: 'Track record statistics', source: pageSource, contentSpec: { stats: [{ value: '500+', label: 'Clients Coached' }, { value: '95%', label: 'Goal Achievement Rate' }, { value: '10+', label: 'Years Experience' }, { value: '4.9★', label: 'Client Rating' }] } });
      components.push({ id: `comp_services_${pageSlug}`, type: 'ServicesGrid', title: 'Coaching Programs', purpose: 'Training program offerings', source: pageSource, contentSpec: null });
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Client Transformations', purpose: 'Real client results', source: pageSource, contentSpec: contentStrategy?.heroContent ? { testimonials: [{ quote: 'Incredible results — highly recommended.', author: 'Client Name', role: 'Coaching Client', rating: 5 }] } : null });
      components.push({ id: `comp_booking_${pageSlug}`, type: 'BookingForm', title: 'Book Free Consultation', purpose: 'Consultation booking form', source: pageSource, contentSpec: null });
    } else if (isRestaurant) {
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Guest Reviews', purpose: 'Social proof from real diners', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Reserve Table CTA', purpose: 'Reservation drive', source: pageSource, contentSpec: { headline: 'Reserve Your Table Today', subheadline: 'Book online for the best dining experience.', actionLabel: 'Make a Reservation' } });
    } else if (isHotel) {
      components.push({ id: `comp_amenities_${pageSlug}`, type: 'AmenitiesGrid', title: 'Hotel Amenities', purpose: 'Key amenity highlights', source: pageSource, contentSpec: null });
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Guest Reviews', purpose: 'Guest social proof', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Booking CTA', purpose: 'Reservation CTA', source: pageSource, contentSpec: { headline: 'Reserve Your Luxury Stay', subheadline: 'Experience the finest hospitality.', actionLabel: 'Enquire & Reserve' } });
    } else if (isSaaS) {
      components.push({ id: `comp_features_${pageSlug}`, type: 'FeatureGrid', title: 'Key Capabilities', purpose: 'Core platform features', source: pageSource, contentSpec: null });
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Customer Success', purpose: 'Customer testimonials', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Demo CTA', purpose: 'Drive demo bookings', source: pageSource, contentSpec: { headline: 'See It in Action', subheadline: 'Book a live product demonstration.', actionLabel: 'Book a Free Demo' } });
    } else if (isBakery) {
      components.push({ id: `comp_catalog_${pageSlug}`, type: 'ItemCatalogGrid', title: "Today's Specialities", purpose: 'Featured treats showcase', source: pageSource, contentSpec: null });
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Happy Customers', purpose: 'Customer reviews', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Custom Order CTA', purpose: 'Drive custom orders', source: pageSource, contentSpec: { headline: 'Planning Something Special?', subheadline: 'Let us create something uniquely crafted for your occasion.', actionLabel: 'Request a Custom Order' } });
    } else if (isPortfolio) {
      components.push({ id: `comp_gallery_${pageSlug}`, type: 'PortfolioGallery', title: 'Selected Works', purpose: 'Featured portfolio preview', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Booking CTA', purpose: 'Drive session enquiries', source: pageSource, contentSpec: { headline: 'Ready to Create Something Extraordinary?', subheadline: 'Available for commercial, editorial and portrait sessions.', actionLabel: 'Book a Session' } });
    } else {
      components.push({ id: `comp_features_${pageSlug}`, type: 'FeatureGrid', title: 'Why Choose Us', purpose: 'Key differentiators', source: pageSource, contentSpec: null });
      components.push({ id: `comp_testimonials_${pageSlug}`, type: 'TestimonialsCarousel', title: 'Client Testimonials', purpose: 'Social proof', source: pageSource, contentSpec: null });
      components.push({ id: `comp_cta_${pageSlug}`, type: 'CallToActionBanner', title: 'Contact CTA', purpose: 'Drive enquiry', source: pageSource, contentSpec: { headline: 'Ready to Get Started?', subheadline: 'Contact us today to discuss your requirements.', actionLabel: 'Get in Touch' } });
    }
  } else if (isMenuPage) {
    components.push({ id: `comp_menu_${pageSlug}`, type: 'RestaurantMenuCard', title: 'Full Menu', purpose: 'Categorized menu with prices and descriptions', source: pageSource, contentSpec: null });
  } else if (isGalleryPage) {
    components.push({ id: `comp_gallery_${pageSlug}`, type: 'PortfolioGallery', title: 'Portfolio Gallery', purpose: 'Filterable gallery of works', source: pageSource, contentSpec: null });
  } else if (isPricingPage) {
    components.push({ id: `comp_pricing_${pageSlug}`, type: 'PricingPlansGrid', title: 'Pricing Plans', purpose: 'Tiered pricing grid', source: pageSource, contentSpec: null });
    components.push({ id: `comp_compare_${pageSlug}`, type: 'ComparisonTable', title: 'Feature Comparison', purpose: 'Plan feature comparison matrix', source: 'ai_recommended', contentSpec: null });
  } else if (isBookingPage) {
    const formType = (nameLower.includes('demo') || purposeLower.includes('demo')) ? 'DemoRequestForm' : 'BookingForm';
    components.push({ id: `comp_booking_${pageSlug}`, type: formType, title: formType === 'DemoRequestForm' ? 'Book a Demo' : 'Book / Reserve', purpose: 'Reservation or demo booking form', source: pageSource, contentSpec: null });
    components.push({ id: `comp_location_${pageSlug}`, type: 'LocationHoursCard', title: 'Location & Hours', purpose: 'Location and operating hours', source: 'ai_recommended', contentSpec: null });
  } else if (isContactPage) {
    components.push({ id: `comp_contact_${pageSlug}`, type: 'ContactInquiryForm', title: 'Contact Form', purpose: 'Enquiry and support form', source: pageSource, contentSpec: null });
    components.push({ id: `comp_location_${pageSlug}`, type: 'LocationHoursCard', title: 'Our Location', purpose: 'Physical location and hours', source: pageSource, contentSpec: null });
  } else if (isAboutPage) {
    components.push({ id: `comp_about_${pageSlug}`, type: 'ContentSectionCard', title: `Our Story`, purpose: pagePurpose, source: pageSource, contentSpec: null });
    components.push({ id: `comp_stats_${pageSlug}`, type: 'StatsCounter', title: 'Track Record', purpose: 'Key statistics and milestones', source: 'ai_recommended', contentSpec: null });
  } else if (isFeaturePage) {
    components.push({ id: `comp_features_${pageSlug}`, type: 'FeatureGrid', title: 'Platform Features', purpose: 'Full feature breakdown', source: pageSource, contentSpec: null });
    components.push({ id: `comp_howitworks_${pageSlug}`, type: 'HowItWorksGrid', title: 'How It Works', purpose: 'Step-by-step workflow', source: 'ai_recommended', contentSpec: null });
  } else if (isCatalogPage) {
    components.push({ id: `comp_catalog_${pageSlug}`, type: 'ItemCatalogGrid', title: 'Product Catalog', purpose: 'Searchable product/service catalog', source: pageSource, contentSpec: null });
  } else if (isServicesPage) {
    components.push({ id: `comp_services_${pageSlug}`, type: 'ServicesGrid', title: 'Our Services', purpose: 'Service listing with pricing', source: pageSource, contentSpec: null });
  } else if (isComparePage) {
    components.push({ id: `comp_compare_${pageSlug}`, type: 'ComparisonTable', title: 'Comparison', purpose: 'Side-by-side feature or spec comparison', source: pageSource, contentSpec: null });
  } else if (isExperiencesPage) {
    components.push({ id: `comp_amenities_${pageSlug}`, type: isHotel ? 'AmenitiesGrid' : 'ServicesGrid', title: 'Experiences & Amenities', purpose: 'Experience and amenity showcase', source: pageSource, contentSpec: null });
  } else if (isOrderPage) {
    components.push({ id: `comp_order_${pageSlug}`, type: 'CustomOrderForm', title: 'Custom Order Form', purpose: 'Bespoke order enquiry form', source: pageSource, contentSpec: null });
  } else if (isRoomPage) {
    components.push({ id: `comp_rooms_${pageSlug}`, type: 'ItemCatalogGrid', title: 'Rooms & Suites', purpose: 'Room category listing', source: pageSource, contentSpec: null });
  } else {
    components.push({ id: `comp_content_${pageSlug}`, type: 'ContentSectionCard', title: `${pageName} Overview`, purpose: pagePurpose, source: pageSource, contentSpec: null });
  }

  return components;
}

/**
 * Synthesizes CTA requirements — uses contentStrategy if available
 */
function synthesizeCTAs(contentStrategy, userRequestedFeatures, approvedRecFeatures, businessType) {
  // Prefer contentStrategy CTA if present (generated by Robert for this specific business)
  if (contentStrategy?.primaryCTA) {
    return {
      primaryCTA: contentStrategy.primaryCTA,
      secondaryCTA: contentStrategy.secondaryCTA || 'Learn More'
    };
  }

  // Fallback: derive from features
  const allFeatures = [...userRequestedFeatures, ...approvedRecFeatures].join(' ').toLowerCase();
  let primaryCTA = 'Contact Us';
  let secondaryCTA = 'Learn More';

  if (allFeatures.includes('reservation') || allFeatures.includes('table') || allFeatures.includes('booking')) {
    primaryCTA = 'Make a Reservation';
    secondaryCTA = 'View Menu';
  } else if (allFeatures.includes('demo') || allFeatures.includes('saas') || allFeatures.includes('software')) {
    primaryCTA = 'Book a Free Demo';
    secondaryCTA = 'View Features';
  } else if (allFeatures.includes('portfolio') || allFeatures.includes('photographer')) {
    primaryCTA = 'Book a Session';
    secondaryCTA = 'View Portfolio';
  } else if (allFeatures.includes('custom') || allFeatures.includes('order')) {
    primaryCTA = 'Request a Custom Order';
    secondaryCTA = 'View Menu';
  } else if (allFeatures.includes('hotel') || allFeatures.includes('resort')) {
    primaryCTA = 'Enquire & Reserve';
    secondaryCTA = 'View Rooms';
  }

  if (allFeatures.includes('whatsapp')) {
    secondaryCTA = 'Chat on WhatsApp';
  }

  return { primaryCTA, secondaryCTA };
}

/**
 * Validates blueprint schema completeness
 */
function validateBlueprintSchema({ blueprintPages, userRequestedFeatures, paymentCheckoutSpec }) {
  const warnings = [];
  if (!blueprintPages || blueprintPages.length === 0) warnings.push('Blueprint contains zero pages.');
  if (!userRequestedFeatures || userRequestedFeatures.length === 0) warnings.push('Zero user-requested features recorded.');
  if (paymentCheckoutSpec.paymentRequired && paymentCheckoutSpec.supportedMethods.length === 0) {
    warnings.push('Payment required but no payment methods specified.');
  }
  return { isValid: warnings.length === 0, warnings };
}

module.exports = { generateWebsiteBlueprint };
